### ISSUE TITLE
Can't pay for yearly subscription for ENVY Pool

### ISSUE THREAD

**Issue by EtherealStakePool** [PaskLab/adastry-ui#14] opened 2023-02-03 04:06 UTC
Hey there! I am trying to pay for the yearly subscription and when I sign and submit, the page sits at transaction processing and then I see that the transaction is stuck at pending on the website (see image below). I tried three times which is why you see it shown three times below. The wallet I tried it from only has 80 ADA in it, so it should only be able to go through once as well. Thank you!
<img width="995" alt="Screenshot 2023-02-02 220545" src="https://user-images.githubusercontent.com/88302563/216510118-25a8ebe5-a189-4e44-aea8-d50bcb8e2983.png">

**Comment by EtherealStakePool** [comment] 2023-02-03 04:15
Also, I noticed that my pool's annual return calculation seems wrong. Is this something that is known?
<img width="639" alt="image" src="https://user-images.githubusercontent.com/88302563/216511143-4e9a0612-059f-4a6a-b35b-520db547b018.png">

**Comment by pascallapointe** [comment] 2023-02-05 04:38
Hey! Thanks for your interest. I will check into this ASAP tomorrow (sunday Feb 4th), didn't get the email notification somehow.

I appreciate you took the time to reach out.

### About Pool Stats
---

No this isn't something known. I did some change in the calculation a few days ago, I probably introduced a bug. Will look into it and get back to you. I tried to quickly emulate your data and I can currently see ROO: 14055.76% ROS: 1.64 %. If you can confirm you get the same.

Pool view will be enhanced in the upcoming months anyways, I quickly added these stats but it is meant to show full pool history in the future 👍.

### About Payment issue
---

Actually I can see you made 5 payments attempt on my backend. I checked all transactions hash and none return a result on cardanoscan explorer.

For some reason the transactions have been successfully built, but never made it to the blockchain. The transaction should be submitted through blockfrost services, but maybe something was down when you attempted it.

I will check with Blockfrost and carry out tests tomorrow to check if the issue remain and let your know. Please wait for my confirmation before attempting another payment.

Thanks again for reporting 🙏 and good job being careful by using an account with only the required amount for payment 👍

Note: Adastry tries to confirm the transaction every 5 minutes for 6 hours before cancelling the payment. Transaction will now be displayed as **cancelled** (I lowered it from 2 days to 6 hours today, might still a little overkill but I'd like to keep room)

**Comment by pascallapointe** [comment] 2023-02-05 20:28
Alright, so after test and research I couldn't find the exact reason why the transaction failed to submit. The logs show nothing related to a submission failure and I can't reproduce the issue.

I can actually think of 3 possibilities:
- There was an unreported issue with Blockfrost
- Wrong system time. The transaction is set to expire after 2 hours and use your system time. A system time offset by more than 2 hours could make the transaction expire before sending. (unlikely that this is the case)
- Usage of a VPN. Already seen a case where a user could not submit through blockfrost while using a VPN (area or IP ban of some sort)

🙏 Please try again and let me know if the issue remain.

---
### Steps & improvements before closing this issue:

- [ ] Fixing pool stats bug
- [ ] Submitting transaction through our own relay instead of relying on Blockfrost
- [ ] Lower the automatic payment cancellation  time to 2 hours to match transaction expiry time
- [ ] Preventing double spending by removing pending transaction from account/pool choice.

**Comment by pascallapointe** [comment] 2023-02-05 21:51
About the stats high number:

The current calculation gives you the mean of all your accounts data mixed together for a given pool.
By being SPO, you can have strange behavior like this when you register an empty account as **pledge account**.

The calculation currently split pool fees among all owners accounts.

The current case is that an account holding ~1 ADA received its share of the fees for some epoch shortly after being registered as owner, so 170ADA for a 1ADA active stake, which throw the number off the rails.

In anycase, I need to rework all this to display the stats on a per account basis instead of mixing everything.
You can ignore current numbers in the mean time.

**Comment by EtherealStakePool** [comment] 2023-02-07 01:00
Hey Pascal. Thank you for the good feedback! I just tried to submit a transaction again and it looks like it went through! 

No worries at all about the pool stats either, I just wanted to make sure you were aware! Looking forward to playing with this tool and offering it to delegators :)

**Comment by pascallapointe** [comment] 2023-02-10 21:15
All features added, closing the issue.
Stats will be rework along will pool section.

**Closed by pascallapointe** 2023-02-10 21:15 UTC
Labels: bug, enhancement
